In [ ]:
import sys

sys.path.append("..")

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

from SpecEmbedding.const import gnps, mona
from SpecEmbedding.data.tokenizer import Tokenizer
from SpecEmbedding.trainer.trainer import ModelTester
from SpecEmbedding.utils.model import (
    cosine_similarity,
    embedding,
    load_transformer_model,
    search,
    search_with_spectra,
)

In [2]:
spectra_paths = {
    "gnps":{
        "orbitrap": {
            "train": (gnps.ORBITRAP_TRAIN_QUERY, gnps.ORBITRAP_TEST_REF),
            "test": (gnps.ORBITRAP_TEST_QUERY, gnps.ORBITRAP_TEST_REF)
        },
        "qtof": {
            "test": (gnps.QTOF_TEST_QUERY, gnps.QTOF_TEST_REF)
        },
        "other": {
            "test": (gnps.OTHER_TEST_QUERY, gnps.OTHER_TEST_REF)
        }
    }
}
gnps_train_ref = np.load(gnps.ORBITRAP_TRAIN_REF, allow_pickle=True)

In [3]:
show_progress_bar = True
is_augment = True
model_backbone = "transformer"
loss_type = "SupConWithTanimotoLoss"
replica_suffix = "-replication-{}"
k_metric = [5, 1, 10]
batch_size = None
loader_batch_size = 4096
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tokenizer = Tokenizer(100, show_progress_bar)
model = load_transformer_model(device, loss_type, is_augment)

tester = ModelTester(model, device, show_progress_bar)

In [4]:
replica_df_seq = []

for i in tqdm(range(10)):
    df_seq = []
    for db, db_metadata in spectra_paths.items():
        for desc, path_metadata in db_metadata.items():
            for info, paths in path_metadata.items():
                print("-" * 40, f"{db}-{desc}-{info}", "-" * 40)
                query_path, ref_path = paths
                query_path = query_path.with_stem(query_path.stem + replica_suffix.format(i + 1))
                ref_path = ref_path.with_stem(ref_path.stem + replica_suffix.format(i + 1))
                if db == "gnps" and desc == "orbitrap":
                    if info == "train":
                        query_path = gnps.ORBITRAP_TRAIN_QUERY
                    
                    ref_spectra = np.load(ref_path, allow_pickle=True)
                    query_spectra = np.load(query_path, allow_pickle=True)
                    ref_spectra = np.hstack((gnps_train_ref, ref_spectra))
                    df = search_with_spectra(
                        f"{db}-{desc}-{info}", tester,
                        k_metric, tokenizer,
                        query_spectra, ref_spectra,
                        loader_batch_size,
                        show_progress_bar, batch_size
                    )
                else:
                    df = search(
                    f"{db}-{desc}-{info}", tester, 
                    k_metric, tokenizer,
                    query_path, ref_path, 
                    loader_batch_size,
                    show_progress_bar, 512
                )
                df_seq.append(df)
    df = pd.concat(df_seq, axis=0)
    print(df)
    replica_df_seq.append(df)

  0%|          | 0/10 [00:00<?, ?it/s]

---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7413.24it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2339426.58it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  1.95it/s]
tokenization: 100%|██████████| 155415/155415 [00:18<00:00, 8630.97it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2220171.03it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.87it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:09<00:00,  9.46s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7613.66it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 3137354.28it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
tokenization: 100%|██████████| 155415/155415 [00:17<00:00, 8742.98it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2129474.69it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.87it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.37s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5106.64it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 1575089.44it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  1.99it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 5834.26it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1913216.67it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.04it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.21it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6639.24it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 2042688.74it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]
tokenization: 100%|██████████| 44241/44241 [00:06<00:00, 6434.62it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 2039571.37it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.88it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.89it/s]
 10%|█         | 1/10 [02:22<21:24, 142.74s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.803678  0.915341  0.939133
gnps-orbitrap-test   0.817912  0.927639  0.947805
gnps-qtof-test       0.503324  0.695346  0.754122
gnps-other-test      0.806852  0.940319  0.959076
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7707.66it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2811386.04it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.24it/s]
tokenization: 100%|██████████| 155415/155415 [00:17<00:00, 8830.70it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2463624.34it/s]
embedding: 100%|██████████| 38/38 [00:21<00:00,  1.81it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:05<00:00,  5.31s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7729.96it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 3254301.22it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.46it/s]
tokenization: 100%|██████████| 155415/155415 [00:17<00:00, 8829.12it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1920765.16it/s]
embedding: 100%|██████████| 38/38 [00:21<00:00,  1.81it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.37s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5461.17it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 1428883.12it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  1.97it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 5734.85it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1098076.92it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.03it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.20it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6726.15it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 2168760.43it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]
tokenization: 100%|██████████| 44241/44241 [00:06<00:00, 6358.42it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 1760967.63it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.89it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:07<00:00,  1.86it/s]
 20%|██        | 2/10 [04:40<18:37, 139.67s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.803970  0.915633  0.938841
gnps-orbitrap-test   0.820878  0.924674  0.947805
gnps-qtof-test       0.506383  0.696543  0.751463
gnps-other-test      0.813672  0.941404  0.959386
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7562.35it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2437870.26it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.23it/s]
tokenization: 100%|██████████| 155415/155415 [00:17<00:00, 8802.56it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2231663.52it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.87it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:05<00:00,  5.29s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7235.61it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 2520169.83it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.50it/s]
tokenization: 100%|██████████| 155415/155415 [00:18<00:00, 8622.01it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2178181.21it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.87it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.47s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5813.11it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 2091866.70it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.00it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 5834.31it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1971510.77it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.02it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:29<00:00,  1.97s/it]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:01<00:00, 5633.51it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 722688.44it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.15it/s]
tokenization: 100%|██████████| 44241/44241 [00:08<00:00, 5141.86it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 1125391.66it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.86it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:07<00:00,  1.69it/s]
 30%|███       | 3/10 [07:25<17:39, 151.34s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.805284  0.915195  0.939133
gnps-orbitrap-test   0.817319  0.930605  0.951364
gnps-qtof-test       0.503989  0.690559  0.748005
gnps-other-test      0.814602  0.943575  0.960006
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7585.92it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2885347.60it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.23it/s]
tokenization: 100%|██████████| 155415/155415 [00:17<00:00, 8793.20it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1703998.36it/s]
embedding: 100%|██████████| 38/38 [00:21<00:00,  1.80it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:05<00:00,  5.91s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 4202.23it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 893781.16it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.07it/s]
tokenization: 100%|██████████| 155415/155415 [00:18<00:00, 8257.10it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2216464.43it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.87it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.48s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5765.17it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 2219801.96it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.00it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 6028.09it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 2007481.94it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.04it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.21it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6630.30it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 2312998.38it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.36it/s]
tokenization: 100%|██████████| 44241/44241 [00:06<00:00, 6469.79it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 2112575.75it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.89it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:07<00:00,  1.85it/s]
 40%|████      | 4/10 [09:45<14:40, 146.77s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.804846  0.915195  0.938841
gnps-orbitrap-test   0.818505  0.927046  0.946026
gnps-qtof-test       0.502660  0.694016  0.751862
gnps-other-test      0.812742  0.940164  0.958301
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:01<00:00, 6660.23it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 1885510.28it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.23it/s]
tokenization: 100%|██████████| 155415/155415 [00:20<00:00, 7491.06it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2288191.67it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.83it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:06<00:00,  6.44s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7398.62it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 3159783.98it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.46it/s]
tokenization: 100%|██████████| 155415/155415 [00:19<00:00, 8104.39it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2185059.10it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.86it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.49s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5777.63it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 1657879.95it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  2.00it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 5928.75it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1911615.85it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.05it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.22it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6704.60it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 2223474.00it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]
tokenization: 100%|██████████| 44241/44241 [00:06<00:00, 6536.81it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 1488375.22it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.90it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.90it/s]
 50%|█████     | 5/10 [12:09<12:08, 145.75s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.804992  0.915487  0.939133
gnps-orbitrap-test   0.810795  0.926453  0.951364
gnps-qtof-test       0.503989  0.688032  0.749867
gnps-other-test      0.807627  0.939854  0.957371
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7596.20it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2674034.68it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.22it/s]
tokenization: 100%|██████████| 155415/155415 [00:20<00:00, 7402.09it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2133447.30it/s]
embedding: 100%|██████████| 38/38 [00:21<00:00,  1.81it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:06<00:00,  6.22s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7248.56it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 2023925.74it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.41it/s]
tokenization: 100%|██████████| 155415/155415 [00:22<00:00, 7059.86it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1640925.75it/s]
embedding: 100%|██████████| 38/38 [00:22<00:00,  1.73it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.80s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 4019.13it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 1107368.12it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  1.94it/s]
tokenization: 100%|██████████| 37040/37040 [00:07<00:00, 4673.01it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1085228.84it/s]
embedding: 100%|██████████| 10/10 [00:05<00:00,  2.00it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.19it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6489.29it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 1811195.87it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]
tokenization: 100%|██████████| 44241/44241 [00:07<00:00, 6180.22it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 1615083.76it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.87it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.86it/s]
 60%|██████    | 6/10 [14:43<09:54, 148.75s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.804846  0.915633  0.938403
gnps-orbitrap-test   0.810795  0.923488  0.945433
gnps-qtof-test       0.506117  0.695213  0.750266
gnps-other-test      0.804526  0.937684  0.958146
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7494.75it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2218076.16it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.21it/s]
tokenization: 100%|██████████| 155415/155415 [00:20<00:00, 7626.16it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1585172.38it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.82it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:06<00:00,  6.42s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7052.53it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 2195466.17it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
tokenization: 100%|██████████| 155415/155415 [00:21<00:00, 7194.54it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1806996.59it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.86it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.48s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5611.76it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 1967510.83it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  2.00it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 5761.67it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1748472.42it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.04it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.20it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:01<00:00, 6434.48it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 1982521.62it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]
tokenization: 100%|██████████| 44241/44241 [00:07<00:00, 6215.19it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 1460230.12it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.88it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.90it/s]
 70%|███████   | 7/10 [17:10<07:24, 148.24s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.804262  0.915049  0.938841
gnps-orbitrap-test   0.812574  0.921115  0.946619
gnps-qtof-test       0.500665  0.695745  0.748138
gnps-other-test      0.809952  0.938304  0.956596
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7378.85it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 1936071.74it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.21it/s]
tokenization: 100%|██████████| 155415/155415 [00:20<00:00, 7416.91it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2105857.81it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.83it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:06<00:00,  6.21s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7490.21it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 3058649.02it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
tokenization: 100%|██████████| 155415/155415 [00:21<00:00, 7229.87it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2148042.14it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.84it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.68s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5619.09it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 2168672.04it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  1.88it/s]
tokenization: 100%|██████████| 37040/37040 [00:07<00:00, 4994.42it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1844919.96it/s]
embedding: 100%|██████████| 10/10 [00:06<00:00,  1.63it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.17it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6512.68it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 2101713.15it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]
tokenization: 100%|██████████| 44241/44241 [00:06<00:00, 6417.01it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 2012627.21it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.89it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.88it/s]
 80%|████████  | 8/10 [19:40<04:57, 148.66s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.804846  0.915925  0.938841
gnps-orbitrap-test   0.815540  0.927639  0.951364
gnps-qtof-test       0.501330  0.692420  0.748138
gnps-other-test      0.809022  0.941559  0.960316
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7422.61it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 2411276.05it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.23it/s]
tokenization: 100%|██████████| 155415/155415 [00:19<00:00, 8107.47it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1475589.19it/s]
embedding: 100%|██████████| 38/38 [00:21<00:00,  1.77it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:06<00:00,  6.20s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7395.68it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 2818492.05it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
tokenization: 100%|██████████| 155415/155415 [00:21<00:00, 7292.87it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2361315.80it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.86it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.77s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5604.67it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 2136211.72it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  2.00it/s]
tokenization: 100%|██████████| 37040/37040 [00:06<00:00, 5802.40it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1904001.72it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.04it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:06<00:00,  2.21it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:01<00:00, 6266.80it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 1850082.40it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]
tokenization: 100%|██████████| 44241/44241 [00:07<00:00, 6122.41it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 1413275.17it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.88it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.91it/s]
 90%|█████████ | 9/10 [22:06<02:27, 147.68s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.805284  0.915633  0.938549
gnps-orbitrap-test   0.811388  0.922301  0.946619
gnps-qtof-test       0.502261  0.695213  0.748803
gnps-other-test      0.806697  0.938924  0.956906
---------------------------------------- gnps-orbitrap-train ----------------------------------------

tokenization: 100%|██████████| 6851/6851 [00:00<00:00, 7384.99it/s]
get smiles: 100%|██████████| 6851/6851 [00:00<00:00, 1852567.64it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.22it/s]
tokenization: 100%|██████████| 155415/155415 [00:18<00:00, 8208.44it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 2146641.54it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.84it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:06<00:00,  6.21s/it]

---------------------------------------- gnps-orbitrap-test ----------------------------------------

tokenization: 100%|██████████| 1686/1686 [00:00<00:00, 7439.58it/s]
get smiles: 100%|██████████| 1686/1686 [00:00<00:00, 2506769.42it/s]
embedding: 100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
tokenization: 100%|██████████| 155415/155415 [00:21<00:00, 7076.19it/s]
get smiles: 100%|██████████| 155415/155415 [00:00<00:00, 1145159.08it/s]
embedding: 100%|██████████| 38/38 [00:20<00:00,  1.84it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:02<00:00,  2.73s/it]

---------------------------------------- gnps-qtof-test ----------------------------------------

tokenization: 100%|██████████| 7520/7520 [00:01<00:00, 5197.39it/s]
get smiles: 100%|██████████| 7520/7520 [00:00<00:00, 1145993.03it/s]
embedding: 100%|██████████| 2/2 [00:01<00:00,  1.94it/s]
tokenization: 100%|██████████| 37040/37040 [00:07<00:00, 4734.82it/s]
get smiles: 100%|██████████| 37040/37040 [00:00<00:00, 1172558.91it/s]
embedding: 100%|██████████| 10/10 [00:04<00:00,  2.02it/s]
calculate hit and recall count: 100%|██████████| 15/15 [00:07<00:00,  1.98it/s]

---------------------------------------- gnps-other-test ----------------------------------------

tokenization: 100%|██████████| 6451/6451 [00:00<00:00, 6576.24it/s]
get smiles: 100%|██████████| 6451/6451 [00:00<00:00, 2131347.39it/s]
embedding: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]
tokenization: 100%|██████████| 44241/44241 [00:07<00:00, 6176.87it/s]
get smiles: 100%|██████████| 44241/44241 [00:00<00:00, 2070683.98it/s]
embedding: 100%|██████████| 11/11 [00:05<00:00,  1.89it/s]
calculate hit and recall count: 100%|██████████| 13/13 [00:06<00:00,  1.88it/s]
100%|██████████| 10/10 [24:34<00:00, 147.46s/it]

                         top1      top5     top10
gnps-orbitrap-train  0.804116  0.915341  0.938549
gnps-orbitrap-test   0.822064  0.923488  0.944247
gnps-qtof-test       0.501064  0.694149  0.750798
gnps-other-test      0.814757  0.942180  0.959541

In [5]:
data = []
indices = replica_df_seq[0].index
columns = replica_df_seq[0].columns
for item in replica_df_seq:
    data.append([item.values])

In [6]:
data = np.concatenate(data, axis=0)
np.set_printoptions(precision=5, suppress=True)
np.mean(data, axis=0) * 100, np.std(data, axis=0) * 100

(array([[80.46125, 91.5443 , 93.88264],
        [81.5777 , 92.54448, 94.78648],
        [50.31782, 69.37234, 75.01463],
        [81.0045 , 94.03968, 95.85646]]),
 array([[0.05351, 0.02532, 0.02481],
        [0.39894, 0.27699, 0.24946],
        [0.18857, 0.25194, 0.18829],
        [0.34954, 0.17293, 0.12383]]))

In [7]:
pd.set_option('display.precision', 4)
mean_df = pd.DataFrame(np.mean(data, axis=0) * 100, index=indices, columns=columns)
std_df = pd.DataFrame(np.std(data, axis=0) * 100, index=indices, columns=columns)

In [8]:
show_progress_bar = False
is_augment = True
model_backbone = "transformer"
loss_type = "SupConWithTanimotoLoss"
replica_suffix = "-replication-{}"
k_metric = [5, 1, 10]
batch_size = None
loader_batch_size = 512
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
tokenizer = Tokenizer(100, show_progress_bar)
model = load_transformer_model(device, loss_type, is_augment)
tester = ModelTester(model, device, show_progress_bar)

query_spectra = np.load("../data/legacy/MSBert/MTBLS1572/query.npy", allow_pickle=True)
ref_spectra = np.load("../data/legacy/MSBert/MTBLS1572/ref.npy", allow_pickle=True)

search_with_spectra(
    "MTBLS1572", tester,
    k_metric, tokenizer,
    query_spectra, ref_spectra,
    loader_batch_size,
    show_progress_bar, batch_size
)

           top1  top5  top10
MTBLS1572   1.0   1.0    1.0

In [9]:
query_embedding, _ = embedding(
    tester, tokenizer,
    512, query_spectra,
    False
)

ref_embedding, _ = embedding(
    tester, tokenizer,
    512, ref_spectra,
    False
)
cosine_score = cosine_similarity(
    query_embedding, ref_embedding
)
for i, j in enumerate(np.argmax(cosine_score, axis=1)):
    if i != j:
        print(f"{i}-th answer is [{ref_spectra[i].get("compound_name")}] but get [{ref_spectra[j].get("compound_name")}]")

In [10]:
show_progress_bar = True
is_augment = True
model_backbone = "transformer"
loss_type = "SupConWithTanimotoLoss"
k_metric = [5, 1, 10]
batch_size = None
loader_batch_size = 512
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
tokenizer = Tokenizer(100, show_progress_bar)
model = load_transformer_model(device, loss_type, is_augment)
tester = ModelTester(model, device, show_progress_bar)

In [11]:
query_spectra = np.load(mona.ORBITRAP_COMMON, allow_pickle=True)
ref_spectra = np.load(gnps.ORBITRAP_ALL, allow_pickle=True)

search_with_spectra(
    "Orbitrap Common", tester,
    k_metric, tokenizer,
    query_spectra, ref_spectra,
    loader_batch_size,
    show_progress_bar, batch_size
)

tokenization: 100%|██████████| 3376/3376 [00:00<00:00, 7008.19it/s]
get smiles: 100%|██████████| 3376/3376 [00:00<00:00, 2396745.14it/s]
embedding: 100%|██████████| 7/7 [00:00<00:00,  7.45it/s]
tokenization: 100%|██████████| 163952/163952 [00:19<00:00, 8398.04it/s]
get smiles: 100%|██████████| 163952/163952 [00:00<00:00, 1507537.04it/s]
embedding: 100%|██████████| 321/321 [00:22<00:00, 14.40it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:04<00:00,  4.01s/it]

                   top1    top5   top10
Orbitrap Common  0.8525  0.9171  0.9396

In [12]:
query_spectra = np.load(mona.QTOF_COMMON, allow_pickle=True)
ref_spectra = np.load(gnps.QTOF_ALL, allow_pickle=True)

search_with_spectra(
    "QTOF Common", tester,
    k_metric, tokenizer,
    query_spectra, ref_spectra,
    loader_batch_size,
    show_progress_bar, batch_size
)

tokenization: 100%|██████████| 7243/7243 [00:01<00:00, 4156.12it/s]
get smiles: 100%|██████████| 7243/7243 [00:00<00:00, 1954409.67it/s]
embedding: 100%|██████████| 15/15 [00:01<00:00, 14.49it/s]
tokenization: 100%|██████████| 44560/44560 [00:10<00:00, 4405.28it/s]
get smiles: 100%|██████████| 44560/44560 [00:00<00:00, 1198718.44it/s]
embedding: 100%|██████████| 88/88 [00:06<00:00, 14.34it/s]
calculate hit and recall count: 100%|██████████| 1/1 [00:01<00:00,  1.85s/it]

               top1    top5   top10
QTOF Common  0.9845  0.9936  0.9977